services:
  postgres:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_strong_pass#}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - search_network

  logstash:
    image: ghcr.io/0xhexe/logstash-postgres/logstash-postgres:8.16.0-pg42.7.4
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/sql:/usr/share/logstash/sql:ro
    env_file:
      - .env
    environment:
      LS_JAVA_OPTS: "${LS_JAVA_OPTS:--Xmx256m -Xms256m}"
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_strong_pass#}
      SYNC_INTERVAL: ${SYNC_INTERVAL:-* * * * *}
    depends_on:
      - postgres
    networks:
      - search_network

networks:
  search_network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch-data:
  